name: earthkit
channels:
- conda-forge
- nodefaults
dependencies:
- earthkit-data>=0.13.8
- geos
- pip:
  - earthkit-geo>=0.3.0
  - earthkit-hydro>=0.1.3
  - earthkit-meteo>=0.3.0
  - earthkit-plots>=0.3.1
  - earthkit-regrid>=0.4.0
  - earthkit-time>=0.1.7
  - earthkit-transforms>=0.4.0
