name: earthkit
channels:
- conda-forge
- nodefaults
dependencies:
- earthkit-data>=0.14.4
- geos
- pip:
  - earthkit-geo>=0.3.0
  - earthkit-hydro>=1.0.0
  - earthkit-meteo>=0.4.1
  - earthkit-plots>=0.3.1
  - earthkit-regrid>=0.4.0
  - earthkit-time>=0.1.7
  - earthkit-transforms>=0.4
  - earthkit-utils>=0.0.1
  - earthkit-workflows>=0.3.6
